project:
  type: website
  output-dir: _site #for the logo to appear

website:
  title: ""
  page-footer: "Made with 💚 and Quarto"
  announcement:
    content: "**NEW** - [**Hands-on Exercise 04**](https://cathyc.netlify.app/hands-on_ex/hands-on_ex04/hands-on_ex04_1) and [**In-class Exercise 03**](https://cathyc.netlify.app/in-class_ex/in-class_ex03) are published!"
    position: below-navbar
    icon: rocket-takeoff-fill
    
  navbar:
    logo: "images/dino.png"
    right:
    - href: index.qmd
      text: "![](images/spinners.svg)"
    - href: about.qmd
      text: "![](images/paw2.svg)"

    left: 
    - text: "**Hands-on Exercise**"
      menu:
      - text: "Hands-on Exercise 0"
        href: Hands-on_Ex/Hands-on_Ex00/Hands-on_Ex00.html
      - text: "Hands-on Exercise 1"
        href: Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html
      - text: "Hands-on Exercise 2"
        href: Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html
      - text: "Hands-on Exercise 3-1"
        href: Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03_1.html
      - text: "Hands-on Exercise 3-2"
        href: Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03_2.html
      - text: "Hands-on Exercise 4-1"
        href: Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04_1.html
      - text: "Hands-on Exercise 4-2"
        href: Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04_2.html
      - text: "Hands-on Exercise 4-3"
        href: Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04_3.html
      - text: "Hands-on Exercise 4-4"
        href: Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04_4.html
      # - text: "Hands-on Exercise 5-1"
      #   href: Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex05_1.html
      # - text: "Hands-on Exercise 5-2"
      #   href: Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex05_2.html
      # - text: "Hands-on Exercise 5-3"
      #   href: Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex05_3.html
      # - text: "Hands-on Exercise 5-4"
      #   href: Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex05_4.html
      # - text: "Hands-on Exercise 6"
      #   href: Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex06.html
      # - text: "Hands-on Exercise 7"
      #   href: Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex07.html
      # - text: "Hands-on Exercise 8"
      #   href: Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex08.html
      # - text: "Hands-on Exercise 9"
      #   href: Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex09.html
    - text: "**In-class Exercise**"
      menu:
      - text: "In-class Exercise 1"
        href: In-class_Ex/In-class_Ex01.html
      - text: "In-class Exercise 2"
        href: In-class_Ex/In-class_Ex02.html
      - text: "In-class Exercise 3"
        href: In-class_Ex/In-class_Ex03.html
      - text: "In-class Exercise 4"
        href: In-class_Ex/In-class_Ex04.html
    - text: "**Take-home Exercise**"
      menu: 
      - text: "Take-home Exercise 1"
        href: Take-home_Ex/Take-home_Ex01.html
      - text: "Take-home Exercise 2"
        href: Take-home_Ex/Take-home_Ex02.html
      - text: "Take-home Exercise 3"
        href: Take-home_Ex/Take-home_Ex03.html
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "![](images/spinners.svg)"
        href: index.qmd
      - section: "Hands-on Exercise"
        href: Hands-on_Ex/Hands-on_Ex00/Hands-on_Ex00.html
        contents:
          - text: "Hands-on_Ex00"
            href: Hands-on_Ex/Hands-on_Ex00/Hands-on_Ex00.html
          - text: "Hands-on_Ex01"
            href: Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html
          - text: "Hands-on_Ex02"
            href: Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html
          - text: "Hands-on_Ex03_1"
            href: Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03_1.html
          - text: "Hands-on_Ex03_2"
            href: Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03_2.html
          - text: "Hands-on_Ex04_1"
            href: Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04_1.html
          - text: "Hands-on_Ex04_2"
            href: Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04_2.html
          - text: "Hands-on_Ex04_3"
            href: Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04_3.html
          - text: "Hands-on_Ex04_4"
            href: Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04_4.html
      - section: "In-class Exercise"
        contents:
          - text: "In-class_Ex1"
            href: In-class_Ex/In-class_Ex01.html
          - text: "In-class_Ex2"
            href: In-class_Ex/In-class_Ex02.html
          - text: "In-class_Ex3"
            href: In-class_Ex/In-class_Ex03.html
      - section: "Take-home Exercise"
        contents:
          - text: "Take-home_Ex01"
            href: Take-home_Ex/Take-home_Ex01.html
      - text: "About"
        href: about.qmd

format:
  html:
    linkcolor: "#db7093"
    theme:
      - cosmo
      - brand
    css: styles.css
    logo: dino.png
    toc: true

editor: visual

brand:
  color:
    background: "#ebf5fb"
    

