---
title: "Hands-on Ex03"
author: "Cathy C"
date-modified: "last-modified" 
execute:
  echo: true 
  eval: true 
  warning: false 
  freeze: true  
---

# Visualising Distribution

## [4-3.1]{style="color:skyblue"} Learning Outcome

## [4-3.2]{style="color:skyblue"} Visual Statistical Analysis with **ggstatsplot**

### [4-3.2.1]{style="color:skyblue"} Installing and launching R packages

### [4-3.2.2]{style="color:skyblue"} Importing data

## [4-3.3]{style="color:skyblue"} Getting started

### [4-3.3.1]{style="color:skyblue"} Installing and launching R packages

### [4-3.3.2]{style="color:skyblue"} Importing data

### [4-3.3.3]{style="color:skyblue"} One-sample test: *`gghistostats()`* method

## [4-3.4]{style="color:skyblue"} Visualsing Models

### [4-3.4.1]{style="color:skyblue"} Installing and launching R packages

### [4-3.4.2]{style="color:skyblue"} Importing data

### [4-3.4.3]{style="color:skyblue"} One-sample test: *`gghistostats()`* method

## [4-3.5]{style="color:skyblue"} Getting started

## [4-3.6]{style="color:skyblue"} Installing and loading the required libraries

### [4-3.6.2]{style="color:skyblue"} Multiple regression model using `lm()`

### [4-3.6.3]{style="color:skyblue"} Model diagnostic: checking for multicolinearity

### [4-3.6.4]{style="color:skyblue"} Model diagnostic: checking normality assumption

### [4-3.6.5]{style="color:skyblue"} Model diagnostic: check model for homogeneity of variances

### [4-3.6.6]{style="color:skyblue"} Model diagnostic: complete check

### [4-3.6.7]{style="color:skyblue"} Visualising regression parameters: see methods

### [4-3.6.8]{style="color:skyblue"} Visualising regression parameters: *`ggcoefstats()`* methods
