---
title: "Take-home_Ex01_working"
author: "Cathy C."
---

```{r}
pacman::p_load(tidyverse)
library(readr)
data_heart <- read_csv("data/jp_heart_attack_dataset.csv")
data_ship <- read_csv("data/Ship_Pfm_Dataset.csv")

data_heart 

data_ship
```

```{r}

df_65plus <- data_heart %>% filter(Age >= 65)
df_40plus <- data_heart %>% filter(Age >= 40)
df_65below <- data_heart %>% filter(Age < 65)

ggplot(df_65plus,
       aes(x = Gender,
           y = BMI, 
           fill = Heart_Attack_Occurrence)) + 
  geom_boxplot() +
  labs(x = "Gender", y = "BMI")


```

```{r}
ggplot(df_65plus,
       aes(x = Gender,
           y = Heart_Rate, 
           fill = Heart_Attack_Occurrence)) + 
  geom_boxplot() +
  labs(title = "Heart rate by gender for 65plus",
  x = "Gender", y = "Heart_Rate")

```

```{r}
ggplot(df_65below,
       aes(x = Gender,
           y = Heart_Rate, 
           fill = Heart_Attack_Occurrence)) + 
  geom_boxplot() +
  labs(title = "Heart rate by gender for 65below",
  x = "Gender", y = "Heart_Rate")

```

```{r}
ggplot(df_65plus,
       aes(x = Region,
           y = Cholesterol_Level, 
           fill = Heart_Attack_Occurrence)) + 
  geom_boxplot() +
  labs(title = "Cholesterol_Level by region for 65below",
  x = "Region", y = "Cholesterol_Level")
```

```{r}
ggplot(df_65plus,
       aes(x = Gender,
           y = Cholesterol_Level, 
           fill = Heart_Attack_Occurrence)) + 
  geom_boxplot() +
  labs(title = "Cholesterol_Level by gender for 65below",
  x = "Gender", y = "Cholesterol_Level")
```

```{r}
ggplot(df_65plus,
       aes(x = Gender,
           y = Diastolic_BP, 
           fill = Heart_Attack_Occurrence)) + 
  geom_boxplot() +
  labs(title = "Diastolic_BP by gender for 65plus",
  x = "Gender", y = "Diastolic_BP")
```

```{r}
ggplot(df_65below,
       aes(x = Gender,
           y = Diastolic_BP, 
           fill = Heart_Attack_Occurrence)) + 
  geom_boxplot() +
  labs(title = "Diastolic_BP by gender for 65below",
  x = "Gender", y = "Diastolic_BP")
```

```{r}
ggplot(df_65plus,
       aes(x = Region,
           y = Diastolic_BP, 
           fill = Heart_Attack_Occurrence)) + 
  geom_boxplot() +
  labs(title = "Diastolic_BP by Region for 65plus",
  x = "Region", y = "Diastolic_BP")
```

```{r}
ggplot(df_65plus,
       aes(x = Region,
           y = Stress_Levels, 
           fill = Heart_Attack_Occurrence)) + 
  geom_boxplot() +
  labs(title = "Stress level by region for 65plus",
       x = "Region", y = "Stress")
```

```{r}
ggplot(df_40plus,
       aes(x = Gender,
           y = Stress_Levels, 
           fill = Heart_Attack_Occurrence)) + 
  geom_boxplot() +
  labs(title = "Stress level by gender for 40plus",
       x = "Gender", y = "Stress")
```

```{r}
ggplot(df_65below,
       aes(x = Gender,
           y = Stress_Levels, 
           fill = Heart_Attack_Occurrence)) + 
  geom_boxplot() +
  labs(title = "Stress level by gender for 65below",
    x = "Gender", y = "Stress")
```

```{r}
ggplot(df_65plus,
       aes(x = Heart_Attack_Occurrence,
           fill = Gender)) + 
  geom_bar() +
  labs(x = "Gender", y = "Count")
```

```{r}
ggplot(df_65below,
       aes(x = Heart_Attack_Occurrence,
           fill = Gender)) + 
  geom_bar() +
  labs(x = "Gender", y = "Count")
```

```{r}
ggplot(df_65plus,
       aes(x = Heart_Attack_Occurrence,
           fill = Family_History)) + 
  geom_bar() +
  labs(x = "Family_History", y = "Count")
```

```{r}
ggplot(df_65plus,
       aes(x = Heart_Attack_Occurrence,
           fill = Physical_Activity)) + 
  geom_bar() +
  labs(x = "Physical_Activity", y = "Count")
```

Age

```{r}
df_agegrp <- data_heart %>%
  mutate(Age_Group = cut(Age, 
                         breaks = c(-Inf, 15, 25, 40, 65, Inf),
                         labels = c("0-15", "16-25", "26-40","41-65", "65+")))

ggplot(df_agegrp,
       aes(x = Heart_Attack_Occurrence,
           fill = Age_Group)) + 
  geom_bar() +
  labs(x = "Age", y = "Count")
```

```{r}
ggplot(data_heart,
       aes(x = Heart_Attack_Occurrence,
           y = Age, 
           fill = Gender)) + 
  geom_boxplot() +
  labs(title = "Age by gender",
       x = "Ht attack", y = "Age")
```
