---
title: "Take-home_Ex02"
author: "Cathy Chu"
date: "February 24, 2025"
date-modified: "last-modified" 
execute:
  echo: true 
  eval: true 
  warning: false 
  freeze: true  
---

## 1 Overview

As a visual analytics novice, I will apply newly acquired techniques to explore and analyze the changing trends and patterns of Singapore’s international trade since 2015. I will be using the [data set](https://www.singstat.gov.sg/find-data/search-by-theme/trade-and-investment/merchandise-trade/latest-data) from the Department of Statistics Singapore (DOS) to re-create visualisations with critics on the visualisations shared on the [DOS website](https://www.singstat.gov.sg/modules/infographics/singapore-international-trade), and analyse the time-series events.

### 1.1 Task

There are 2 tasks I will complete in this page.

1.  Critics on 3 chosen visualisations from the Department of Statistics Singapore. I will provide sketches of improved version and use R packages to re-create the visualisations for clearer messaging.
2.  I will analyse the data with time-series analysis with data visualisation methods and R packages.

### 1.2 Data

## 2 Visualisation Make-Over

### 2.1 Data

### 2.2 Critiques

### 2.3 Sketches

### 2.4 Visualisation #1

#### 2.4.1 Data

#### 2.4.2 Make-over

### 2.5 Visualisation #2

#### 2.5.1 Data

#### 2.5.2 Make-over

### 2.6 Visualisation #3

#### 2.6.1 Data

#### 2.6.2 Make-over

### 2.7 Summary

## 3 Singapore Merchandise Trade Data Analysis

Analyse the data with either time-series analysis or time-series forecasting methods by compliment the analysis with appropriate data visualisation methods and R packages.

### 3.1 Objectives

### 3.2 Data

### 3.3 Analysis

visualisation methods, analysis results (500 words)

## 4 Conclusion

## Reference
