---
title: "Take-home_Ex01_working"
author: "Cathy C."
---

``` r
pacman::p_load(ggstatsplot)
```

``` r
pacman::p_load(tidyverse)
library(readr)
data_heart <- read_csv("data/jp_heart_attack_dataset.csv")
data_ship <- read_csv("data/Ship_Pfm_Dataset.csv")
```

``` r
#glimpse(data_ship)
```

**Numerical Features**

-   Speed_Over_Ground_knots: Average speed of the ship over water (in knots).
-   Engine_Power_kW: Engine power output (in kilowatts).
-   Distance_Traveled_nm: Total distance traveled by the ship (in nautical miles).
-   Operational_Cost_USD: Total operational cost per voyage (in USD).
-   Revenue_per_Voyage_USD: Revenue generated per voyage (in USD).
-   Efficiency_nm_per_kWh: Energy efficiency calculated in nautical miles per kilowatt-hour.

**Categorical Features**

-   Ship_Type: Type of ship (e.g., Tanker, Container Ship, Fish Carrier, Bulk Carrier).
-   Route_Type: Shipping route type (e.g., Short-haul, Long-haul, Transoceanic).
-   Engine_Type: Type of engine (e.g., Diesel, Heavy Fuel Oil).
-   Maintenance_Status: Maintenance condition of the ship (e.g., Fair, Critical, Good).
-   Weather_Condition: Prevailing weather conditions during voyages (e.g., Calm, Moderate, Rough).

| Packages | Description |
|-------------------------------------|-----------------------------------|
| tidyverse | the tidyverse package installs a number of other packages for reading data and data manilupation, tidying. |
| ggplot2 | a system for declaratively creating graphics. |
| colorspace | provides a broad toolbox for selecting individual colors or color palettes, manipulating these colors, and employing them in various kinds of visualizations. |
| egg | High-level functions are provided to post-process 'ggplot2' layouts and allow alignment between plot panels, as well as setting panel sizes to fixed values. |
| geomtextpath | 3.09 |
| gganimate | 3.09 |
| ggdist | 3.09 |
| ggstatsplot | 3.09 |
| ggtext | 3.09 |
| ggthemes | 3.09 |
| ggridges | 3.09 |
| haven | 3.09 |
| knitr | 3.09 |
| magrittr | 3.09 |
| patchwork | 3.09 |
| performance | 3.09 |
| parameters | 3.09 |
| readxl | 3.09 |
| RColorBrewer | 3.09 |
| see | 3.09 |
| tidyverse | 3.09 |

: {tbl-colwidths="\[20,80\]"}

::::: spgoals
::: spgoals-header
Insights
:::

::: spgoals-container
-   text
:::

``` r
#| fig-width: 15
#| fig-height: 8
#| code-fold: true
#| code-summary: "Show the code"

# Plot1
# Plot statboxplot by ship types
p_statbox_st <- ggbetweenstats(
  data = ship_filter,
  x = Ship_Type,
  y = Profit,
  type = "p",
  mean.ci = TRUE,
  pariwise.comparisons = TRUE,
  pairwise.display = "s",
  p.adjust.methods = "fdr",
  message = FALSE
) +
    coord_flip() 

#Plot raincloud plot by ship types
median_Profit <- median(ship_filter$Profit)
mean_Profit <- round(mean(ship_filter$Profit), 2)

p_rcloud_st <- ggplot(ship_filter,
       aes(x = Ship_Type,
           y = Profit,
           fill = Ship_Type)) +
  stat_halfeye(adjust = 0.3,
               justification = -0.2,
               scale = 0.6,
               width = 0.6,
               slab_color = "grey",
               slab_fill = "#D6DED5",
               slab_linetype = "solid",
               slab_linewidth = 0.4,
               slab_alpha = 0.5,
               .width = 0,
               point_colour = NA,
               position = position_nudge(y = -0.2)) +
  geom_boxplot(width = 0.1,
               color = "#FFC0CB",
               position = position_nudge(y = 0.8)) +
  scale_fill_brewer(palette="Pasterl1") +
  stat_dots(side = "left",
            justification = 1.2,
            bandwidth = .5,
            dotsize = 0.1,
            alpha = 0.4,
            aes(color = Engine_Type)) +
  #indicate median score position
  geom_hline(aes(yintercept = median_Profit),
             color = "blue", 
             linewidth = 0.4,
             linetype = "dashed") +
  #indicate mean score position
  geom_hline(aes(yintercept = mean_Profit),
             color = "red", 
             linewidth = 0.4,
             linetype = "dashed") +
  theme_minimal() +
  annotate("text",
           x = 0.1,
           y = median_Profit + 270,
           label = paste("Median Score = ", median_Profit),
           color = "blue",
           size = 3) +
  
  annotate("text",
           x = 0.3,
           y = mean_Profit + 270,
           label = paste("Mean Score = ", mean_Profit),
           color = "red",
           size = 3) +
  coord_flip() +
  theme_light() +
  theme(plot.background = element_rect(fill = "#f1f4f5"),
        panel.background = element_rect(fill = "#f1f4f5"),
        panel.border = element_blank())

#Combine two plots
patchwork <- (p_rcloud_st | p_statbox_st)
patchwork
```
:::::
