---
title: "Hands-on_Ex03_1"
author: "Cathy Chu"
date-modified: "last-modified" 
execute:
  echo: true 
  eval: true 
  warning: false 
  freeze: true
---

## **Programming Interactive Data Visualisation with R**

## [3.1]{style="color:skyblue"} Learning Outcome
In this hands-on exercise, you will learn how to create interactive data cisualisation by using functions provided by **ggiraph** and **plotlyr** packages.

## [3.2]{style="color:skyblue"} Getting Started
First, write a code chunk to check, install and launch t he following R packages:

-   ggiraph for making 'ggplot' graphics interactive.
-   plotly, R library for plotting interactive statistical graphs
-   DT provides an R interface to the JavaScript library DataTables that create interactive table on html page.
-   tidyverse, a family of modern R packages specially designed to support data science, analysis and communication task including creating static statistical graphs.
-   patchwork for combining multple ggplot2 graphs into one figure.

## [3.3]{style="color:skyblue"} Importing Data

## [3.4]{style="color:skyblue"} Interactive Data Visualisation - ggiraph methods

## [3.5]{style="color:skyblue"} Interactivity

## [3.6]{style="color:skyblue"} Interactivity - customisation

## [3.7]{style="color:skyblue"} Interactive Data Visualisation - plotly methods!

## [3.8]{style="color:skyblue"} Interactive Data Visualisation - crosstalk methods!

## [3.9]{style="color:skyblue"} Reference
